title: JetObsMC
description: Unified jet observables for Monte Carlo validation in the HEPSIM / ML4SCI context.
url: "https://atharva12081.github.io"
baseurl: "/JetObsMC"
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
